
set -g base-index 1
setw -g pane-base-index 1
set -g mouse on

set-option -g renumber-windows on

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind r source-file ~/.config/tmux/tmux.conf \; display "Config recargada"

set -g default-terminal "screen-256color"
set -as terminal-features ",xterm-256color:RGB"

setw -g automatic-rename on

set -g set-titles on
set -g set-titles-string "#{pane_current_command}"


setw -g window-status-current-format ' #I#[fg=colour235]:#[fg=colour235]#{pane_current_command}#F '
setw -g window-status-format ' #I#[fg=colour239]:#[fg=colour243]#{pane_current_command}#[fg=colour239]#F '
# --- GRUVBOX MATERIAL DESIGN ---

# Colores de la paleta Gruvbox Material (Medium)
# Background: #282828 (colour235)
# Foreground: #dfbf8e (colour223)
# Aqua: #89b482 (colour108)
# Yellow: #d8a657 (colour172)
# Orange: #e78a4e (colour167)
# Grey: #7c6f64 (colour243)

# Reloj (Aqua)
setw -g clock-mode-colour colour108

# Modo copia (Selección)
setw -g mode-style 'fg=colour235 bg=colour108 bold'

# Paneles (Bordes discretos)
set -g pane-border-style 'fg=colour239'
set -g pane-active-border-style 'fg=colour172'

# Barra de estado
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=colour223 bg=colour235'

set -g status-left ''
set -g status-left-length 10

# Derecha: Fecha y hora (Fondo Orange, texto oscuro)
set -g status-right-style 'fg=colour235 bg=colour167'
set -g status-right ' %Y-%m-%d │ %H:%M '
set -g status-right-length 50

# Ventana actual (Yellow / Cream) - Ahora con comando dinámico
setw -g window-status-current-style 'fg=colour235 bg=colour172 bold'
setw -g window-status-current-format ' #I#[fg=colour235]:#[fg=colour235]#{pane_current_command}#F '

# Ventanas en segundo plano (Gris suave) - Ahora con comando dinámico
setw -g window-status-style 'fg=colour243 bg=colour235'
setw -g window-status-format ' #I#[fg=colour239]:#[fg=colour243]#{pane_current_command}#[fg=colour239]#F '

# Mensajes (Comandos)
set -g message-style 'fg=colour223 bg=colour239 bold'
