#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox

exec-once = hyprlock -c /home/matias/dotfiles/hypr/.config/hypr/hyprlock/hyprlock.conf

exec-once = swww-daemon
exec-once = /home/matias/BashScripts/monitor-wallpaper.sh

exec-once = zen-browser
exec-once = discord
exec-once = [workspace 3 silent] steam

# Cliphist daemon para el historial de copiados
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
